name: Ashley workflow

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Dar permisos al script
        run: chmod +x ./github_push.sh

      - name: Ejecutar script de Ashley
        run: ./github_push.sh
