name: Ashley Bot Core

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Dar permisos de ejecución al script
        run: chmod +x ./github_push.sh

      - name: Ejecutar script de Ashley
        run: ./github_push.sh
